#!/bin/bash

# This script should echo only the name of the profile that should be used
# It should assume it is called before any other scripts. In particular, it
# cannot rely on environment variables set in /etc/profile or elsewhere. The
# script may assume it will be run as root.

echo "home"
