.\"
.\" CopyLeft (c) 2015 -tclover <tokiclover@gmail.com>
.\"
.\" Distributed under the terms of the GNU General Plublic License version 2
.\" as pugblished by the Free Software Fondation, Inc.
.\"
.pc
.TH HPROFILE 1 "2015-01-01" "3.2.0" "Hprofile Script Page"
.SH NAME
hprofile \- profiles management tool
.SH DESCRIPTION
.B hprofile
require either
.IR bash
(for 3.x branch) or
.IR zsh
(for 4.x branch).
The tool can manage multiple profile, be it hardware, or sotware related.
A
.BI profile
(in hprofile terms) is just a directory containing child profile scripts
and extra files to be swaped, actualy symlinked, when the appropriate profile
becomes active. See
.B LAYOUTS
and
.B FILES
sub-sections for more info on the layout of a (parrent) profile.
.SH SYNOPSIS
The following conventions apply to
.B SYNOPSIS
and
.B LAYOUTS
sections and is also applicable to the command line arguments.
.TS
tab (@);
l lx.
\fBbold text\fR@T{
type exactly as shown
T}
\fIitalic text\fR@T{
replace with appropriate argument
T}
[\|text\|]@T{
any or all argument within [ ] are optional
T}
.TE

.B hprofile
.RB [\| \-f|\-\-force \|]
.RB [\| \-u|\-\-user= \|\c
.RI \| <user> \|]
.RI \| <type> \|\c
.RB [\| .\fI<profile>\fR \|]

.B hprofile
.RB [\| \-c|\-\-current= \|\c
.RI \| <type> \|]
.RB [\| \-l|\-\-list= \|\c
.RI \| <type> \|]
.RB [\| \-r|\-\-revert= \|\c
.RI \| <type> \|]
.RB [\| \-s|\-\-stop= \|\c
.RI \| <type> \|]
.RB [\| \-t|\-\-type \|]

.B hprofile
.RB [\| \-h|\-\-help \|]
.RB [\| \-v|\-\-version \|]
.SH LAYOUTS
A hprofile
.I <PROFILE>
is a directory hierarchy that may contain the following files.
Almost everything is optional, meaning a profile could have only child profile
`scripts/*.{start,stop}'. Start/Stop scripts can be used as a shared script
between child profiles, and thus, can be used like `start <ARGS>' or `stop <ARGS>'
in the child profiles.
Pre/Post-{Start,Stop} script can be used to do common tasks when starting or
stopping a child profile.

To sum up, only `\fI<PROFILE>\fR/profiles' file is required along with at least
a `scripts/*.start' file for each child profile to define a valid profile.
.TP
.B /etc/hprofile/profiles/\fI<PROFILE>\fR
.TS
tab (@);
l lx.
\fBdefault\fR@T{
Default child profile to use when starting (parent) profile type (optional)
T}
\fBptest\fR@T{
Dynamic profile probing script to determine which (child) profile to use (optional)
T}
\fBprofiles\fR@T{
List supported (chid) profiles (required)
T}
\fBstart\fR@T{
Start (common) script and can be used by child profiles (optional)
T}
\fBstop\fR@T{
Stop (common) script and can be used by child profiles (optional)
T}
\fBpost-start\fR@T{
Start-Script to execute after starting a child profile (optional)
T}
\fBpre-start\fR@T{
Start-Script to execute before starting a chid profile (optional)
T}
\fBpost-stop\fR@T{
Stop-Script to execute after stopping a child profile (optional)
T}
\fBpre-stop\fR@T{
Stop-Script to execute before stopping a child profile (optional)
T}
\fBfiles/**/*.<profile>\fR@T{
Files hierarchy to swap (or rather symlink) when a child profile become active
T}
\fBscripts/\fR\fI<profile>\fR\fB.start\fR@T{
Child profile activation Start-Script (required for each child profile)
T}
\fBscripts/\fR\fI<profile>\fR\fB.stop\fR@T{
Child profile deactivation Stop-Script (optional for each child profile)
T}
\fI<SCRIPT>\fR\fB.$SHELL\fR@T{
Each file found would be defined as a function (to ease execution)
T}
.TE
.RE

When a child profile becomes active, files found in `<PROFILE>/files' directory
with the extension `<profile>' are symlinked to the file system (without the
`/etc/hprofile/profiles/<PROFILE>/files'.)
.SH CONFIGURATION
.SH EXAMPLES
.SH FILES
.TP
.BR /etc/{conf,init}.d/hprofile
.B hprofile
init service script along with its configuration file.
.TP
.BR /etc/hprofile/hprofile.conf
Main
.B hprofile
configuration file.
.TP
.BR /etc/hprofile/profiles/PROFILES
.TP
.B PROFILES

Each profile has a files hierarchy and (child-)profiles.
The following (child-)profile name scheme conventions that apply to
.B PROFILES
sub-section and can be applied to the following (parrent) profiles.
.TS
tab (@);
l lx.
\fBadp\fR@T{
AC power adaptater connected
T}
\fBbat\fR@T{
AC power adaptater disconnected (battery profile)
T}
\fBdyn\fR@T{
Dynamic hprofile (AC power may be connected or not)
T}
\fBquiet\fR@T{
Quiet profile (silence oriented profile)
T}
\fBmed\fR@T{
Medium profile (balence between qerformance & quiet)
T}
.TE
.TP
.SS disk
.br
.RB ata.$SHELL
.RB default
.RB post-start
.RB profiles
.RB ptest
.RB scripts/{adp,bat,dyn,quiet}.start
.RB usb.$SHELL

This profile is tailored to manage hard disk drive and thus depends on hdparm.
.TP
.SS power
.br
.RB default
.RB profiles
.RB ptest
.RB scripts/{adp,bat,dyn,med,quiet}.start
.RB start

This profile was made to be a superset of other profiles, so it depends on disk
profile. Other profiles can be added (like rfkill profile, for example.)
.TP
.SS rfkill
.br
.RB default
.RB profiles
.RB scripts/{bsw,ksw,wsw}.{start,stop}

RFKill wireless radio profile (Note: B for Bluetooth, W for Wireless, K for Kill, and
SW for SWitch.)
.TP
.SS vga
.br
.RB default
.RB post-start
.RB post-stop
.RB profiles
.RB ptest
.RB scripts/{fglrx,intel,nouveau,nv,nvidia,radeon}.{start,stop}
.RB files/etc/X11/xorg.conf.d/40-monitor.conf.{fglrx,intel,nouveau,nv,nvidia,radeon}

Graphics Hardware (GPU) profile that can be used to switch between different
hardware and or drivers.
.br
.B WARNING: This profile should be used out of X server.
.SH AUTHORS
-tclover <tokiclover@hprofile.project>
.\"
.\" vim:fenc=utf-8:ft=groff:ci:pi:sts=2:sw=2:ts=2:expandtab:
.\"
