#!/sbin/runscript
# Copyright 1999-2002 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License, v2 or later


depend() {
	after *
}

start() {
	# Change runlevel if necessary
	profile=$(/usr/local/sbin/hpdet boot)
	runlevel=$(/usr/local/sbin/hprunlevel "${profile}")
	if [ runlevel != "" ]
	then
	  ebegin "Setting runlevel for hardware profile ${profile}"
	  /sbin/init "${runlevel}"
	  eend $?
	fi
}


# vim:ts=4
