#!/sbin/runscript
#
# $Header: /etc/init.d/hprofile,v 1.4 2015/05/05         Exp $
#

description="Soft/hardware profiles utility service"

depend()
{
	after modules
}

start()
{
	local p
	for p in ${PROFILES}; do
		ebegin "Starting ${p} profile"
		hprofile -f ${p}
		eend "${?}"
	done
	return 0
}

stop()
{
	local p
	for p in ${PROFILES}; do
		ebegin "Stopping ${p} profile"
		hprofile -s ${p}
		eend "${?}"
	done
	return 0
}

#
# vim:fenc=utf-8:ft=gentoo-init-d:ci:pi:sts=0:sw=4:ts=4:
#
