#!/bin/sh
#
# Header: hprofile
# Aythor:
# 	Copyright (c) 2003-2004 Martin Aspeli <optilude@gmx/net>
# 	Copyright (c) 2014-2015 -tclover <tokiclover@gmail.com>
# License: GPL-2
#

if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	setopt SH_WORD_SPLIT
	setopt EXTENDED_GLOB NULL_GLOB
	disable -r end
elif [ -n "${BASH_VERSION}" ]; then
	shopt -qs nullglob
	shopt -qs extglob
fi

PKG=hprofile
VERSION=5.0.0
CONFDIR=/etc/hprofile
NULL=/dev/null
name=${PKG}

if [ -f "${CONFDIR}/${PKG}.conf" ]; then
	source "${CONFDIR}/${PKG}.conf"
fi

#
# @FUNCTION: Print error message to stderr
#
error()
{
	local prefix=${name:+" ${CLR_MAG}${name}:${CLR_RST}"}
	echo -e${eol+n} "${eol+\n} ${CLR_RED}*${CLR_RST}${prefix} ${@}" >&2
}

#
# @FUNCTION: Print error message to stderr & exit
#
die()
{
	local ret=${?}; error "${@}"; exit ${ret}
}

#
# @FUNCTION: Print info message to stdout
#
info()
{
	local prefix=${name:+" ${CLR_YLW}${name}:${CLR_RST}"}
	echo -e${eol+n} "${eol+\n} ${CLR_BLU}*${CLR_RST}${prefix} ${@}"
}

#
# @FUNCTION: Print warn message to stdout
#
warn()
{
	local prefix=${name:+" ${CLR_RED}${name}:${CLR_RST}"}
	echo -e${eol+n} "${eol+\n} ${CLR_YLW}*${CLR_RST}${prefix} ${@}"
}

#
# @FUNCTION: Print begin message to stdout
#
begin()
{
	[ -n "${eol}" ] && echo
:	${eol=0}
	local prefix=${name:+"${CLR_MAG}[${CLR_RST} ${CLR_BLU}${name}${CLR_RST}: ${CLR_MAG}]${CLR_RST}"}
	echo -en " ${prefix} ${@}"
}

#
# @FUNCTION: Print end message to stdout
#
end()
{
	local suffix
	case "${1-0}" in
		(0) suffix="${CLR_BLU}[${CLR_RST} ${CLR_GRN}Ok${CLR_RST} ${CLR_BLU}]${CLR_RST}";;
		(*) suffix="${CLR_YLW}[${CLR_RST} ${CLR_RED}No${CLR_RST} ${CLR_YLW}]${CLR_RST}";;
	esac
	shift
	echo -en " ${@} ${suffix}\n"
	eol=
}

yesno()
{
	case "${1:-NO}" in
	(0|[Dd][Ii][Ss][Aa][Bb][Ll][Ee]|[Oo][Ff][Ff]|[Ff][Aa][Ll][Ss][Ee]|[Nn][Oo])
		return 1;;
	(1|[Ee][Nn][Aa][Bb][Ll][Ee]|[Oo][Nn]|[Tt][Rr][Uu][Ee]|[Yy][Ee][Ss])
		return 0;;
	(*)
		return 2;;
	esac
}

#
# @FUNCTION: Colors handler
#
eval_colors()
{
	local BLD ESC FGD clr
	BLD='1;' ESC='\e[' FGD='3'

	for clr in 0:BLK 1:RED 2:GRN 3:YLW 4:BLU 5:MAG 6:CYN 7:WHT; do
		eval CLR_${clr#*:}="'${ESC}${BLD}${FGD}${clr%:*}m'"
	done
	CLR_RST="${ESC}0m"
}

if [ -t 1 ] && yesno "${COLOR:-Yes}"; then
	eval_colors
fi

usage()
{
	cat <<-EOH
  usage: ${PKG} [options] <type>[.<profile>]

    -d, --debug              Enable debug mode
    -t, --type               Print all known profiles types
    -c, --current=<type>     Print the current profile <type>
    -p, --profile=<type>     Print the profile that would be used
    -l, --list=<type>        Print all available <type> profiles
    -s, --stop=<type>        Stop the current <type> profile
    -u, --user=<user>        Use a user profile instead of system wide
    -h, --help               Print this help message
    -v, --version            Print pkgname-version_string
    -r, --revert=<type>      Revert to the previous known <type> profile
    -f, --force              Apply profile regardless of the current one

  <type>                     Switch to the currently valid <type> profile
  <type>.<profile>           Switch to the given <type>.<profile> profile
EOH
${1:+exit ${1}}
}

version()
{
	echo -e "${CLR_BLU}${PKG}${CLR_RST} version ${CLR_MAG}${VERSION}${CLR_RST}"
	exit
}

#
# @FUNCTION: Validity verification of a profile type
# @ARGS: <type>
#
verify_profile()
{
	[ "${#}" = 1  ] && [ -n "${1}"   ] || die "Invalid profile type ${1}"
	[ -n "${dir}" ] && [ -d "${dir}" ] || local dir="${DIR}/profiles/${1}"

	[ -e "${dir}/ptest"   ] || [ -f "${dir}/profiles"  ] ||
	[ -f "${dir}"/default ] || [ -e "${dir}"/start_pre ] ||
	[ -e "${dir}"/start_post ] || die "Invalid profile type ${2}"
}

#
# @FUNCTION: Print the profile to be used
# @ARGS: <type> <profile>
#
get_profile()
{
	local dir="${DIR}/profiles/${1}" name="${2}"

	[ -z "${name}" ] && [ -s "${dir}/ptest"   ] && name=$(run_script "${dir}/ptest")
	[ -z "${name}" ] && [ -s "${dir}/default" ] && name=$(cat "${dir}/default")

	[ -z "${name}" ] && [ -s "${profiles}" ] &&
		name=$(sed -nre '0,/^[a-zA-Z].*/p' "${profiles}")

	echo "${name}"
}

#
# @FUNCTION: Print the currently selected profile
# @ARGS: <type>
#
current_profile()
{
	local file="${DIR}/profiles/${1}/current"
	[ -s "${file}" ] && echo $(cat "${file}")
}

#
# @FUNCTION: run script passed as positional parameter 1
# @ARGS: <script> <args>
#
run_script()
{
	[ "${#}" -ge 1 ] && [ -s "${1}" ] || return
	local func="${1}"

	local src tail
	for src in ${dir}/*[:alnum:]*.sh; do
		[ -s "${src}" ] || continue
		tail="${src##*/}"
		eval "${tail%.sh}() { source \"${src}\"; }"
	done

	shift
	eval "script() { source \"${func}\"; }"
	script "${@}"

	return 0
}

#
# @FUNCTION: Stop the current profile of the given type
# @ARGS: <inherited>|<type> <profile>
#
stop_profile()
{
	[ -n "${1}" ] && local type="${1}" dir="${DIR}/profiles/${1}"
	local current="$(current_profile)"
	[ -n "${current}" ] && local profile="${current}" || return 0

	echo -e "Stoping ${CLR_GRN}${type}.${CLR_YLW}${profile}${CLR_RST} profile"

	if [ -s "${dir}/stop" ]; then
		stop() { source "${dir}/stop"; }
	fi
	for scr in stop_pre scripts/${profile}.stop stop_post; do
		if [ -s "${dir}/${scr}" ]; then
			run_script "${dir}/${scr}" "${profile}" ||
				die "Failed to run ${type}/${scr} script"
		fi
	done
	echo              > "${DIR}/profiles/${type}/current"
	echo "${profile}" > "${DIR}/profiles/${type}/previous"
}

#
# @FUNCTION: Revert to the previous profile of the given type
# @ARGS: <type>
#
revert_profile()
{
	local file="${DIR}/profiles/${1}/previous"
	[ -s "${file}" ] && local previous=$(cat "${file}") || return
	[ -n "${previous}" ] && start_profile "${1}" "${previous}"
}

#
# @FUNCTION: Print all known profile types
#
profile_type()
{
	for dir in "${DIR}/profiles"/*; do
		verify_profile "${dir}" && echo -n "${dir##*/} "
	done
	echo
	exit
}

#
# @FUNCTION: Print all valid profiles of the given type
# @ARGS: <type>
#
profile_list()
{
	local dir="${DIR}/profiles/${1}"

	if [ -s "${dir}/profiles" ]; then
		echo $(cat "${dir}/profiles")
	else
		local tail
		for file in "${dir}"/scripts/*.start; do
			tail="${file##*/}"
			echo "${file%.start}"
		done
	fi
	exit
}

#
# @FUNCTION: Swap files with extension .<profile> in the appropriate profile
# directory, and sym-link files appropriately.
# @ARGS: <inherited>
#
swap_files()
{
	local filesdir="${dir}/files" src dest

	for src in $(find "${filesdir}" -name "*.${profile}"); do
		dest="${src#${filesdir}}"
		dest="${dest%.${profile}}"
		if [ -e "${dest}" ] && [ ! -h "${dest}" ]; then
			if ! diff "${dest}" "${src}" >${NULL}; then
				mv -f "${dest}" "${dest}\~" || die "Failed to back up ${dest} file"
			fi
		fi
		ln -fs "${src}" "${dest}" || die "Failed to restore ${src} to ${dest}"
	done
}

#
# @FUNCTION: Apply profile
# @ARGS: <type> <profile>
#
start_profile()
{
	local type="${1}" profile="${2}"
	local dir="${DIR}/profiles/${1}"

	echo -e "Starting ${CLR_GRN}${type}.${CLR_YLW}${profile}${CLR_RST} profile"

	# Stop profile
	stop_profile
	# Start profile
	if [ -s "${dir}/start" ]; then
		start() { source "${dir}/start"; }
	fi
	for scr in start_pre scripts/${profile}.start start_post; do
		if [ -s "${dir}/${scr}" ]; then
			run_script "${dir}/${scr}" "${profile}" ||
				die "Failed to run ${type}/${scr} script"
		fi
	done
	# Sym-link files if available
	if [ -d "${dir}/files" ]; then
		swap_files || die "Failed to swap ${type}.${profile} files"
	fi
	# Save profile
	echo "${profile}" >"${DIR}/profiles/${type}/current"
}

[ ${#} -ge 1 ] || usage 2

DIR="${CONFDIR}"

ARGS="$(getopt \
	-l debug,force,help,version,profile:,type,current:,list:,stop:,revert,user: \
	-o \?dfhvtc:p:l:s:r:u: -n ${PKG} -s sh -- "${@}")"
[ ${?} = 0 ] || usage 1
eval set -- "${ARGS}"

while true; do
	case "${1}" in
		(-d|--debug) set -x ; shift;;
		(-f|--force) FORCE=1; shift;;
		('-?'|-h|--help) usage 0;;
		(-v|--version) version;;
		(-t|--type)	profile_type;;
		(-c|--current)
			verify_profile  "${2}"
			current_profile "${2}"
			exit;;
		(-p|--profile)
			verify_profile "${2}"
			get_profile    "${2}"
			exit;;
		(-l|--list)
			verify_profile "${2}"
			profile_list   "${2}";;
		(-s|--stop)
			verify_profile "${2}"
			stop_profile "${2}" && exit || die "Could not stop ${2} profile"
			;;
		(-r|--revert)
			verify_profile "${2}"
			revert_profile "${2}"
			exit;;
		(-u|--user) DIR="${HOME}/.${PKG}";;
		(*) shift; break;;
	esac
done

set ${@/./ }
NAME="${2}"
TYPE="${1}"

[ -n "${TYPE}" ] || die "Empty/null profile type"
verify_profile "${TYPE}"

[ -n "${NAME}" ] || NAME=$(get_profile "${TYPE}")
[ -n "${NAME}" ] || die "Could not find ${NAME} profile ${TYPE}"

CURRENT=$(current_profile "${TYPE}")
if [ "${NAME}" = "${CURRENT}" ]; then
	[ -n "${FORCE}" ] || exit 0
fi
start_profile "${TYPE}" "${NAME}"

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
